#!/usr/bin/env bash
# Transfer a file from a client to a server using scp
# This script accepts 4 arguments:

# The path to the file to be transferred
FILE=$1

# The IP of the server to transfer the file to
SERVER=$2

# The username scp connects with on the server
USER=$3

# The path to the SSH key to use for authentication
KEY=$4

# Check that the correct number of arguments were passed
if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER"@"$SERVER":~/
