#!/usr/bin/env bash
# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Allow nginx through the firewall (UFW) on port 80
sudo ufw allow 'Nginx HTTP'

# Add an index.html file to the root directory
sudo echo "Hello World" > /var/www/html/index.html

# Start nginx
sudo service nginx start
