#!/usr/bin/env bash
# Configure nginx server so that /redirect_me is redirected to another page
# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Change ownership of the /var/www/ directory
sudo chown -R "$USER":"$USER" /var/www/

# Add an index.html file to the root directory
echo "Hello World!" > /var/www/html/index.html

# Store the context as a variable
CONTEXT="\tlocation /redirect_me {\n\t\treturn 301 \
https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-enabled/default"

# Check if the context is already in the config file
if grep -q "location /redirect_me {" $FILE; then
    echo "Context already in config file."
else
    # Add the context to the default nginx config file
    sudo sed -i --follow-symlinks "/PHP scripts to/i\ $CONTEXT" $FILE
fi

# Check if nginx is running
if sudo service nginx status | grep -q "running"; then
    # Reload nginx
    sudo nginx -s reload
else
    # Start nginx
    sudo service nginx start
fi
