#!/usr/bin/env bash
# Configure nginx server to return a custom 404 page

# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Change ownership of the various directories nginx uses
sudo chown -R "$USER":"$USER" /var/www/ /etc/nginx/ /usr/share/nginx/

# Add a custom home and 404 page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Store the redirection and error_page contexts as a variable
CONTEXT="\tlocation /redirect_me {\n\t\treturn 301 \
https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \
/custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot \
/usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

# Add the context to the default nginx config file
sed -i "/pass PHP scripts/ i\ $CONTEXT" /etc/nginx/sites-available/default

# Link the changed config file to the sites-enabled directory
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Start nginx
sudo service nginx start
