#!/usr/bin/env bash
# Configure nginx server to return a custom 404 page based on 3-redirection

# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Change ownership of the various directories nginx uses
sudo chown -R "$USER":"$USER" /var/www/ /usr/share/nginx/html/

# Add a custom home and 404 page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Store the redirection and error_page contexts as a variable
CONTEXT="\terror_page 404 /custom_404.html;\n\tlocation = \
/custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

# Check if the context is already in the config file
if grep -q "error_page 404 /custom_404" /etc/nginx/sites-enabled/default; then
    echo "Context already in config file."
else
    # Add the context to the default nginx config file
    sudo sed -i "/pass PHP script/i\ $CONTEXT" /etc/nginx/sites-enabled/default
fi

# Check if nginx is running
if sudo service nginx status | grep -q "active (running)"; then
    # Reload nginx
    sudo nginx -s reload
else
    # Start nginx
    sudo service nginx start
    sudo nginx -s reload
fi
