#!/usr/bin/env bash
# Configure nginx server add a custom header with the server name as value

# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Change ownership of the various directories nginx uses
sudo chown -R "$USER":"$USER" /var/www/ /usr/share/nginx/html/

# Add a custom home and 404 page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Store the context as a variable
CONTEXT="\tadd_header X-Served-By \$hostname always;"

# Check if the context is already in the config file
if grep -q "add_header X-Served-By" /etc/nginx/nginx.conf; then
    echo "Context already in nginx config."
else
    # Add the context to the default nginx config file
    sudo sed -i "/sendfile/i\ $CONTEXT" /etc/nginx/nginx.conf
fi

# Check if nginx is running
if sudo service nginx status | grep -q "active (running)"; then
    # Reload nginx
    sudo nginx -s reload
else
    # Start nginx
    sudo service nginx start
    sudo nginx -s reload
fi
