#!/usr/bin/env bash
# Configure nginx server add a custom header with the server name as value

# Install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y

# Change ownership of the various directories nginx uses
sudo chown -R "$USER":"$USER" /var/www/ /usr/share/nginx/html/

# Add a custom home and 404 page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Store the context as a variable
# shellcheck disable=SC2154
# CONTEXT="\tadd_header X-Served-By $HOSTNAME;\n"
CONTEXT="\tlocation /redirect_me {\n\t\treturn 301 \
https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \
/custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot \
/usr/share/nginx/html;\n\t\tinternal;\n\t}\n\n\tadd_header X-Served-By \
\$hostname;\n"

# Check if the context is already in the config file
if grep -q "location /redirect_me {" /etc/nginx/sites-enabled/default; then
    echo "Context already in config file."
else
    # Add the context to the default nginx config file
    sudo sed -i "/pass PHP script/i\ $CONTEXT" /etc/nginx/sites-enabled/default
fi

# Check if nginx is running
if sudo service nginx status | grep -q "active (running)"; then
    # Reload nginx
    sudo nginx -s reload
else
    # Start nginx
    sudo service nginx start
    sudo nginx -s reload
fi
