#!/usr/bin/env bash
# Checks if a device/host is available on the network

DEVICE=$1
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$DEVICE"
