#!/usr/bin/env bash
# Debug an nginx installation that's not listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
echo -n > /run/nginx.pid
