#!/usr/bin/env bash
# Creates a file named /var/run/myscript.pid that contains its PID.

echo $$ > /var/run/myscript.pid

# Handle the SIGTERM, SIGINT and SIGQUIT signals
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

# Display 'To infinity and beyond' indefinitely
while true ; do
    echo "To infinity and beyond"
    sleep 2
done
