#!/usr/bin/env bash
# Display numbers 1 to 100, replacing multiples of 3 with Fizz, 
#+ multiples of 5 with Buzz, and multiples of both 3 and 5 with FizzBuzz.

for i in {1..100}; do
	if ((i % 15 == 0)); then
		echo "FizzBuzz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	else
		echo "$i"
	fi
done
