#!/usr/bin/env bash
# Display "Best School" 10 times using a while loop except on the 4th
# and 8th iterations. Display "bad luck" then "good luck" instead.

i=1
while [ $i -le 10 ] ; do
    if [ $i -eq 4 ] ; then
	echo "bad luck"
    elif [ $i -eq 8 ] ; then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((i++))
done
