#!/usr/bin/env bash
# This script displays the numbers 1 to 20 and displays "bad luck from China"
# after the 4th number, "bad luck from Japan" after the 9th number, and
# "bad luck from Italy" after the 17th number using 'case'

i=1
while [ $i -le 21 ] ; do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    i=$((i+1))
done
