#!/usr/bin/env bash
# Gives information about the school file.

file="school"
# Check if the file exists.
if [ -e "$file" ] ; then
	echo "$file file exists"
	# Check if the file is a regular file, empty or not.
	if [ -s "$file" ] ; then
		echo "$file file is not empty"
		if [ -f "$file" ] ; then
			echo "$file file is a regular file"
		fi
	else
		echo "$file file is empty"
	fi
else
	echo "$file file does not exist"
fi

