#!/usr/bin/env bash
# Display information about the "school" file.

filename="school"
# Check if the file exists.
if [ -e "$filename" ] ; then
	echo "$filename file exists"
	# Check if the file is empty or not.
	if [ -s "$filename" ] ; then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi
	# Check if the file is a regular file.
	if [ -f "$filename" ] ; then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
