#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic except
# ports 22 (SSH), 443 (HTTPS SSL) and 80 (HTTP) on an nginx server
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
